### ISSUE TITLE
enable to define a variable in forcefield

### ISSUE THREAD

**Issue by ToruNiina** [Mjolnir-MD/Mjolnir#113]
Generally, to pass a forcefield as an input file, we need to write many parameters. For most parameters, there are really few different values compared to the number of parameters need to be written. The reason is that some of the particles might represent the same atom or pseudo-atom (like a group of atoms).

It is probably good to enable to define a variable in a toml file. There are several reasons like the following.
- one can explicitly represent some of the parameter values are the same 
  - i.e. one can ensure the values of the parameters means the same thing
- one can reduce the input file size. It takes less effort to write.

Something like this. The format may change later.
```toml
[[forcefield.local]]
type = "BondLength"
potential = "Harmonic"
topology = "bond"
parameter.C-H_energy = 98.7
parameter.C-H_length = 1.09
parameters = [
    {indices = [0, 1], v0 = "C-H_length", k = "C-H_energy"},
    {indices = [1, 2], v0 = "C-H_length", k = "C-H_energy"},
    # ...
]
```

**Comment by ToruNiina** [comment]
Having both `parameter` and `parameters` seems to be confusing. There are some other options like `let`, `var` and `env` that looks more like a variable definition.

```toml
let.C-H_length = 1.09
var.C-H_length = 1.09
env.C-H_length = 1.09
```

Considering the meanings, having a table named "let" might not be so nice. It is just a syntax sugar, not the let expression. In that sense, `var` or `env` is better.
