### ISSUE TITLE
enable to choose output content

### ISSUE THREAD

**Issue by ToruNiina** [Mjolnir-MD/Mjolnir#114]
Currently, `observer` always outputs position and velocity. But one may don't need to have a distribution of velocities. Or one may want to have a time course of forces. So it is good to have an option to choose which values to be written.

The difficult thing is that the file content depends on the format. Some format can only have one vector per one particle, but others can have an arbitrary number of parameters per one particle. The input file format should be united. Thus the way to choose the file content should be considered carefully.

Something like this.
```toml
[files]
output.format = "xyz"
output.content = ["position", "velocity"]
# or
[files]
output.position = "xyz"
output.velocity = "xyz"
```
