### ISSUE TITLE
move `simulator.parameters` to `simulator.integrator.parameters`

### ISSUE THREAD

**Issue by ToruNiina** [Mjolnir-MD/Mjolnir#47]
Currently, parameters for an integrator are given in `[simulator]` table. But the parameters are for the integrator, not for the simulator itself.

It might be confusing. By moving `parameters` from just under `[simulator]` to [simulator.integrator], it becomes clearer.

To do this, we also need to move `integrator` value to `integrator.type` because the type of `integrator` becomes a `toml::table`.

So the `[simulator]` table will be like this.

```toml
[simulator]
type = "Molecular Dynamics"
integrator.type = "Underdamped Langevin"
integrator.parameters = [
    {index = 0, gamma = 0.1},
    # ...
]
```
