### ISSUE TITLE
rename T_begin/end

### ISSUE THREAD

**Issue by ToruNiina** [Mjolnir-MD/Mjolnir#54]
SimulatedAnnealingSimulator requires the following parameters.

```toml
[simulator]
schedule = "linear"
T_begin  = 300.0
T_end    =  10.0 
```

I think the following format is clearer.

```toml
[simulator]
schedule.type  = "linear"
schedule.begin = 300.0
schedule.end   = 10.0
```
